"""miton talent: candidates, events, searches

Revision ID: a0c6f94ba5a9
Revises: 
Create Date: 2026-09-29 09:49:58.627679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c6f94ba5a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_identifier', sa.String(length=255), nullable=True),
    sa.Column('alister_profile_url', sa.String(length=500), nullable=True),
    sa.Column('alister_profile_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('legacy_ref', sa.String(length=255), nullable=True),
    sa.Column('area', sa.JSON(), nullable=False),
    sa.Column('level', sa.JSON(), nullable=False),
    sa.Column('work_mode', sa.JSON(), nullable=False),
    sa.Column('search_status', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('cv_filename', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_position', sa.String(length=255), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('sourced_for', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hiring_review', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('company_tier', sa.String(length=8), nullable=True),
    sa.Column('education_tier', sa.String(length=8), nullable=True),
    sa.Column('fit_areas', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=64), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('interviewed_with', sa.JSON(), nullable=False),
    sa.Column('newsletter', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_legacy_ref'), ['legacy_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_linkedin_identifier'), ['linkedin_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_stage'), ['stage'], unique=False)
        batch_op.create_index('ix_candidates_stage_created', ['stage', 'created_at'], unique=False)

    op.create_table('searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alister_shortlist_id', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('legacy_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searches_legacy_ref'), ['legacy_ref'], unique=False)

    op.create_table('candidate_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_events_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_events_search_id'), ['search_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_events_type'), ['type'], unique=False)

    op.create_table('search_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('founder_rating', sa.String(length=16), nullable=True),
    sa.Column('founder_comment', sa.Text(), nullable=True),
    sa.Column('miton_comment', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'candidate_id', name='uq_search_candidate')
    )
    with op.batch_alter_table('search_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_candidates_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_candidates_search_id'), ['search_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_candidates_search_id'))
        batch_op.drop_index(batch_op.f('ix_search_candidates_candidate_id'))

    op.drop_table('search_candidates')
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_events_type'))
        batch_op.drop_index(batch_op.f('ix_candidate_events_search_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_events_candidate_id'))

    op.drop_table('candidate_events')
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_legacy_ref'))

    op.drop_table('searches')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_stage_created')
        batch_op.drop_index(batch_op.f('ix_candidates_stage'))
        batch_op.drop_index(batch_op.f('ix_candidates_linkedin_identifier'))
        batch_op.drop_index(batch_op.f('ix_candidates_legacy_ref'))
        batch_op.drop_index(batch_op.f('ix_candidates_email'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
